version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3003:3000
    volumes:
      - ../../volumes/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - ../../volumes/homepage/icons:/app/public/icons # optional, for custom icons
    restart: unless-stopped